window.DRIVE_VOCABULARY = [
  ["cordially","진심으로, 정성껏"],["inauguration","개관식, 취임식"],["fine arts","예술, 미술"],
  ["celebration","축하 행사"],["officially","공식적으로"],["browse","둘러보다, 훑어보다"],
  ["exhibit","전시, 전시품"],["spacious","넓은, 널찍한"],["launch party","출시 기념 행사"],
  ["invitation","초대, 초대장"],["nearly","거의"],["arrange","마련하다, 준비하다"],
  ["destination","목적지"],["maintenance crew","정비 요원"],["compulsory","의무적인"],
  ["property management","재산 관리"],["legal right","법적 권리"],["accompany","동행하다"],
  ["against the law","법에 반하는"],["smoke detector","연기 탐지기"],["municipal","시의, 지방 자치의"],
  ["comply with","준수하다"],["strict","엄격한"],["penalty","처벌, 벌금"],
  ["in advance","미리"],["fire alarm","화재 경보기"],["hinder","저해하다, 방해하다"],
  ["boiler","보일러"],["beyond repair","수리할 수 없을 정도의"],["replace","교체하다"],
  ["insect","곤충, 벌레"],["infestation","해충의 침입"],["obligate","의무를 지우다"],
  ["shift","교대 근무"],["overtime","초과 근무, 시간 외 수당"],["cover","대신하다, 다루다"],
  ["graduation","졸업식"],["count out","제외하다"],["out of town","도시를 떠나서"],
  ["minor","사소한, 작은"],["sales counter","판매대, 계산대"],["worsen","악화시키다"],
  ["fall through","무산되다"],["drop by","잠시 들르다"],["speedy","빠른, 신속한"],
  ["recovery","회복"],["take responsibility for","~을 책임지다"],["particular","특정한, 특별한"],
  ["prior","이전의, 앞의"],["commitment","약속, 전념"],["seriously","심각하게"],
  ["resume","다시 시작하다, 재개하다"],["verify","확인하다"],["visitor log","방문자 일지"],
  ["up-to-date","최신의"],["register","등록하다"],["whereabouts","소재, 행방"],
  ["procedure","절차"],["identification","신분 증명"],["verification","확인"],
  ["washroom","화장실"],["in the spotlight","세상의 주목을 받다"],["come together","모이다"],
  ["offering","강좌, 제공되는 것"],["rare opportunity","드문 기회"],["keynote talk","기조 강연"],
  ["aspiring","장차 ~가 되려는"],["lead singer","리드 보컬"],["treat A to B","A에게 B를 대접하다"],
  ["navigate","길을 찾다, 웹사이트를 돌아다니다"],["drop-down menu","드롭다운 메뉴"],
  ["legible","읽기 쉬운"],["color scheme","색채 배합"],["intend for","~을 위해 만들다"],
  ["malfunction","오작동"],["in accordance with","~에 부합하게"],["place an order","주문하다"],
  ["supplement","보충제"],["notification","알림"],["at the latest","늦어도"],
  ["clinical","임상의"],["nutritional","영양의"],["researcher","연구원"],
  ["inquire","문의하다"],["delivery","배송, 배달"],["refund","환불"],
  ["non-government organization","비정부 조직"],["funding","자금"],["conduct","수행하다, 행하다"],
  ["proper","적절한"],["nutrition","영양 섭취"],["orderly","정돈된, 질서 있는"],
  ["unnecessary","불필요한"],["clutter","잡동사니, 어수선함"],["lifetime","평생, 생애"],
  ["charity","자선 단체"],["contribution","공헌, 기부금"],["assemble","조립하다"],
  ["lean against","~에 기대다"],["coordinator","진행자, 조정자"],["spare","여분의, 예비용의"],
  ["training session","교육 시간"],["advisor","고문, 상담가"],["sign up for","~에 등록하다"],
  ["consultant","자문 위원, 상담가"],["corporate","회사의, 법인의"],["executive","경영진, 간부"],
  ["secure","잠그다, 안전하게 하다"],["storage room","창고"],["plenty of","많은"],
  ["reservation","예약"],["vegetarian","채식주의자"],["oversee","감독하다"],
  ["administrative","관리의, 경영상의"],["fluent","유창한"],["transfer","전근 가다"],
  ["get wind of","소문을 듣다"],["extended leave","장기 휴가"],["recruit","신입사원을 모집하다"],
  ["hire","고용하다"],["facility","시설"],["overqualified","필요 이상의 자격을 갖춘"],
  ["obtain","얻다"],["evaluation","평가"],["committee","위원회"],["formal","공식적인"],
  ["depend on","~에 달려 있다"],["cash flow statement","현금 흐름표"],["shareholder","주주"],
  ["compile","자료를 수집하다"],["questionable","확실치 않은, 의심스러운"],["transaction","거래"],
  ["be out sick","아파서 결근하다"],["run out of time","시간이 다 되다"],["invoice","송장"],
  ["assignment","업무, 임무"],["accurate","정확한"],["width","폭, 너비"],
  ["intersection","교차로"],["crossing","건널목"],["roadside","길가, 노변"],
  ["drainage","배수 시설"],["in phases","단계적으로"],["timely","때에 알맞은, 적시의"],
  ["transit","운송, 수송"],["round the clock","계속해서, 밤낮없이"],["grand opening","개점, 개장"]
];
